### ISSUE TITLE
Extract board as component

### ISSUE THREAD

**Issue by Vages** [Vages/svelte-snake-workshop#28]
A lot of CSS goes into creating the board in every task. For instance, this long, identical of CSS is found in the `+page.svelte` in every task:

```css
	.board {
		--border-width: var(--cell-size);
		width: calc(var(--board-size-x) * var(--cell-size));
		height: calc(var(--board-size-y) * var(--cell-size));

		position: relative;
		margin: var(--border-width);
		outline: var(--border-width) solid black;

		background-image: linear-gradient(
				45deg,
				var(--checker-color) 25%,
				transparent 25%
			),
			linear-gradient(-45deg, var(--checker-color) 25%, transparent 25%),
			linear-gradient(45deg, transparent 75%, var(--checker-color) 75%),
			linear-gradient(-45deg, transparent 75%, var(--checker-color) 75%);
		background-size: calc(var(--cell-size) * 2) calc(var(--cell-size) * 2);
		background-position: 0 0, 0 var(--cell-size),
			var(--cell-size) calc(-1 * var(--cell-size)),
			calc(-1 * var(--cell-size)) 0;
	}
```

A lot of this could possibly be helped by extracting the board as a separate component.
Perhaps the task of rendering the snake should be delegated this component as well.

It's important that whatever changes we introduce will be a natural extension of the the tasks' flow.
For instance, many of the early tasks are about placing the different components on the board using CSS.

Currently, components are introduced in part 5.
Perhaps we could introduce them earlier.
